export const pics = [
{"id":1, "name": "Luke Skywalker", "url": "https://s1.thcdn.com/productimg/960/960/11146559-5784309644769473.jpg"},
{"id":2, "name": "C-3PO", "url": "https://images-na.ssl-images-amazon.com/images/I/81qo3DyZWYL._SX425_.jpg"},
{"id":3, "name": "R2-D2", "url": "https://www.swarovski.com/medias/?context=bWFzdGVyfHJvb3R8MzMxMzV8aW1hZ2UvanBlZ3xoNWQvaDhjLzkwMTg5MzI4NTQ4MTQuanBnfDE5Y2JmMWM0MTczNTFiMGY5MzZlZGRhNTJmNWJjODE4MTBkYTBmMDFhYzJiMjJlMzAzYjhiODdlOGQ3MGNjMWQ"},
{"id":4, "name": "Darth Vader", "url": "https://www.swarovski.com/medias/?context=bWFzdGVyfHJvb3R8NTY1NjV8aW1hZ2UvanBlZ3xoNmIvaDk4LzkwMTUwMTM5OTg2MjIuanBnfDIyMzI2MDI3MjhjZmFiNDk0YzMzMDZlNTk3NGQxNTJiOGMxM2Y5ZTMyMWVmNmYzNGY5OTFhMGQ0NzMwOWI3YTU"},
{"id":5, "name": "Leia Organa", "url": "https://d26oc3sg82pgk3.cloudfront.net/files/media/edit/image/2803/square_thumb%403x.jpg"},
{"id":6, "name": "Owen Lars", "url": "https://lumiere-a.akamaihd.net/v1/images/databank_owenlars_01_169_effce0f8.jpeg?region=230%2C0%2C878%2C878&width=320"},
{"id":7, "name": "Beru Whitesun lars", "url": "https://lumiere-a.akamaihd.net/v1/images/databank_berulars_01_169_68101518.jpeg?region=76%2C0%2C877%2C878&width=320"},
{"id":8, "name": "R5-D4", "url": "https://img.brickowl.com/files/image_cache/larger/lego-r5-d8-r5-d4-minifigure-25.jpg"},
{"id":9, "name": "Biggs Darklighter", "url": "https://vignette.wikia.nocookie.net/swfanon/images/5/57/BiggsDarklighter.jpg/revision/latest?cb=20120324222406"},
{"id":10, "name": "Obi-Wan Kenobi", "url": "https://media.forbiddenplanet.com/products/3c3cdb8681cc6ea3d50aaaa744ba42cb3d6f11b4.jpg"},
{"id":11, "name":  "", "url": ""},
{"id":12, "name":  "", "url": ""},
{"id":13, "name":  "", "url": ""},
{"id":14, "name":  "", "url": ""},
{"id":15, "name":  "", "url": ""},
{"id":16, "name":  "", "url": ""},
{"id":17, "name":  "", "url": ""},
{"id":18, "name":  "", "url": ""},
{"id":19, "name": "", "url": ""},
{"id":20, "name": "", "url": ""},
{"id":21, "name":  "", "url": ""},
{"id":22, "name":  "", "url": ""},
{"id":23, "name":  "", "url": ""},
{"id":24, "name":  "", "url": ""},
{"id":25, "name":  "", "url": ""},
{"id":26, "name":  "", "url": ""},
{"id":27, "name":  "", "url": ""},
{"id":28, "name":  "", "url": ""},
{"id":29, "name": "", "url": ""},
{"id":30, "name": "", "url": ""},
{"id":31, "name":  "", "url": ""},
{"id":32, "name":  "", "url": ""},
{"id":33, "name":  "", "url": ""},
{"id":34, "name":  "", "url": ""},
{"id":35, "name":  "", "url": ""},
{"id":36, "name":  "", "url": ""},
{"id":37, "name":  "", "url": ""},
{"id":38, "name":  "", "url": ""},
{"id":39, "name": "", "url": ""},
{"id":40, "name": "", "url": ""},
{"id":41, "name":  "", "url": ""},
{"id":42, "name":  "", "url": ""},
{"id":43, "name":  "", "url": ""},
{"id":44, "name":  "", "url": ""},
{"id":45, "name":  "", "url": ""},
{"id":46, "name":  "", "url": ""},
{"id":47, "name":  "", "url": ""},
{"id":48, "name":  "", "url": ""},
{"id":49, "name": "", "url": ""},
{"id":50, "name": "", "url": ""},
{"id":51, "name":  "", "url": ""},
{"id":52, "name":  "", "url": ""},
{"id":53, "name":  "", "url": ""},
{"id":54, "name":  "", "url": ""},
{"id":55, "name":  "", "url": ""},
{"id":56, "name":  "", "url": ""},
{"id":57, "name":  "", "url": ""},
{"id":58, "name":  "", "url": ""},
{"id":59, "name": "", "url": ""},
{"id":60, "name": "", "url": ""},
{"id":61, "name":  "", "url": ""},
{"id":62, "name":  "", "url": ""},
{"id":63, "name":  "", "url": ""},
{"id":64, "name":  "", "url": ""},
{"id":65, "name":  "", "url": ""},
{"id":66, "name":  "", "url": ""},
{"id":67, "name":  "", "url": ""},
{"id":68, "name":  "", "url": ""},
{"id":69, "name": "", "url": ""},
{"id":70, "name": "", "url": ""},
{"id":71, "name":  "", "url": ""},
{"id":72, "name":  "", "url": ""},
{"id":73, "name":  "", "url": ""},
{"id":74, "name":  "", "url": ""},
{"id":75, "name":  "", "url": ""},
{"id":76, "name":  "", "url": ""},
{"id":77, "name":  "", "url": ""},
{"id":78, "name":  "", "url": ""},
{"id":79, "name": "", "url": ""},
{"id":80, "name": "", "url": ""},
{"id":81, "name":  "", "url": ""},
{"id":82, "name":  "", "url": ""},
{"id":83, "name":  "", "url": ""},
{"id":84, "name":  "", "url": ""},
{"id":85, "name":  "", "url": ""},
{"id":86, "name":  "", "url": ""},
{"id":87, "name":  "", "url": ""},
{"id":88, "name":  "", "url": ""},
{"id":89, "name":  "", "url": ""},
{"id":90, "name":  "", "url": ""},

]